services:
  # PostgreSQL Database
  db:
    image: postgres:17
    container_name: supabase_db
    restart: unless-stopped
    ports:
      - "54322:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    volumes:
      - supabase_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  # PostgREST API
  rest:
    image: postgrest/postgrest:v12.2.0
    container_name: supabase_rest
    restart: unless-stopped
    ports:
      - "54321:3000"
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@db:5432/postgres
      PGRST_DB_SCHEMAS: public
      PGRST_DB_ANON_ROLE: postgres
      PGRST_JWT_SECRET: your-super-secret-jwt-token-with-at-least-32-characters-long
    depends_on:
      db:
        condition: service_healthy

volumes:
  supabase_db_data: